# Generated by Django 3.2.7 on 2021-10-06 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_alter_players_games'),
    ]

    operations = [
        migrations.RenameField(
            model_name='players',
            old_name='playeremail',
            new_name='email',
        ),
    ]
