# Generated by Django 3.2.7 on 2021-10-06 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_rename_playeremail_players_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='players',
            old_name='email',
            new_name='playeremail',
        ),
    ]
